// Generated by CoffeeScript 1.3.3
var Search;

Search = (function() {

  function Search(query) {
    var _this = this;
    this.query = query;
    this.header = this.buildHeader();
    this.noResultsStr = "<div class='no_result'>\n  <p>We couldn't find any results for your query, <span class='query'>" + (this.stringify(this.query)) + "</span>.\n  <p>Please try another search or head back to the <a href='/'>Documentation Main page</a>.</p>\n</div>";
    this.results = this.getSearchResults(this.query, function(data) {
      var result, resultsJSON, _i, _len;
      _this.result_html = "";
      if (data.results.length) {
        resultsJSON = data.results;
        for (_i = 0, _len = resultsJSON.length; _i < _len; _i++) {
          result = resultsJSON[_i];
          _this.result_html += _this.convertJSONtoHTML(result);
        }
      } else {
        _this.result_html = _this.noResultsStr;
      }
      return _this.renderResults();
    });
  }

  Search.prototype.getSearchResults = function(query, callback) {
    return $.getJSON("" + basepath + "/search/" + query + "?format=json&amp;callback=?", function(data) {
      return callback(data);
    });
  };

  Search.prototype.stringify = function(str) {
    return str.replace(/_/g, ' ');
  };

  Search.prototype.convertJSONtoHTML = function(json) {
    var description, title, url;
    title = json.title;
    description = json.description;
    url = json.url;
    return "<div class='result'>\n  <h2><a href='" + basepath + url + "'>" + title + "</a></h2> \n  <p class='description'>" + description + "</p>\n</div>";
  };

  Search.prototype.buildHeader = function() {
    var html_end_str, html_start_str, result;
    html_start_str = "<div class='results_header'><h1>";
    html_end_str = "</h1></div>";
    result = this.query ? "Results for " + (this.stringify(this.query)) : "enter a search to begin";
    return "" + html_start_str + result + html_end_str;
  };

  Search.prototype.renderResults = function() {
    if (this.result_html) {
      return $('#results').append(this.header).append(this.result_html);
    } else {
      return $('#results').append(this.header);
    }
  };

  return Search;

})();

$(function() {
  var docSearch, query;
  query = (window.location.href.split('?')[1] || "").split('=')[1];
  return docSearch = new Search(query);
});
