// Generated by CoffeeScript 1.3.3
var Search;

Search = (function() {

  function Search() {
    var _this = this;
    this.query = (window.location.href.split('?')[1] || "").split('=')[1];
    this.header = this.buildHeader();
    this.getSearchResults(this.query, function(data) {
      var result, resultsJSON, _i, _len;
      _this.result_html = "";
      if (data.results.length) {
        resultsJSON = data.results;
        for (_i = 0, _len = resultsJSON.length; _i < _len; _i++) {
          result = resultsJSON[_i];
          _this.result_html += _this.convertJSONtoHTML(result);
        }
      } else if (_this.query != null) {
        console.log("noResultsStr");
        _this.result_html = _this.noResultsStr(_this.query);
      } else {
        console.log("suggestedSearchesStr");
        _this.result_html = _this.suggestedSearchesStr();
      }
      return _this.renderResults();
    });
  }

  Search.prototype.getSearchResults = function(query, callback) {
    return $.getJSON("" + basepath + "/search/" + query + "?format=json&amp;callback=?", function(data) {
      return callback(data);
    });
  };

  Search.prototype.stringify = function(str) {
    return str.replace(/_/g, ' ');
  };

  Search.prototype.noResultsStr = function(query) {
    return "<div class='no_result'>\n  <p>We couldn't find any results for your query, <span class='query'>" + (this.stringify(query)) + "</span>.\n  <p>Please try another search or head back to the <a href='/'>Documentation Main page</a>.</p>\n</div>";
  };

  Search.prototype.suggestedSearchesStr = function() {
    return "<h2 class='suggested-title'>Need some suggestions?</h2>\n<div class='result'>\n  <h2><a href='" + basepath + "/media'>Guide to Using Media in Wistia</a></h2> \n  <p class='description'>From changing the title, to embedding it on your \n  website or blog, learn all the functionality for uploaded media here.</p>\n</div>\n<div class='result'>\n  <h2><a href='" + basepath + "/projects'>Guide to Using Projects in Wistia</a></h2> \n  <p class='description'>Projects are where you store, organize, and access \n  media. Projects are the building blocks for Wistia organization.</p>\n</div>\n<div class='result'>\n  <h2><a href='" + basepath + "/wistia-basics'>Wistia Basics Video Series</a></h2> \n  <p class='description'>If you are getting started, or just need a little \n  refresher, the Wistia Basics series is just what you need. Join Chris and \n  Jeff as they take you through the key features and workflows of Wistia, \n  to make sure you get the most out of your account.</p>\n</div>";
  };

  Search.prototype.convertJSONtoHTML = function(json) {
    var description, title, url;
    title = json.title;
    description = json.description;
    url = json.url;
    return "<div class='result'>\n  <h2><a href='" + basepath + url + "'>" + title + "</a></h2> \n  <p class='description'>" + description + "</p>\n</div>";
  };

  Search.prototype.buildHeader = function() {
    var html_end_str, html_start_str, resultHeaderText;
    html_start_str = "<div class='results_header'><h1>";
    html_end_str = "</h1></div>";
    resultHeaderText = (this.query != null) && this.query.length > 0 ? "Results for " + (this.stringify(this.query)) : "Enter a search to begin";
    return "" + html_start_str + resultHeaderText + html_end_str;
  };

  Search.prototype.renderResults = function() {
    console.log("renderResults", this.result_html);
    return $('#results').append(this.header).append(this.result_html);
  };

  return Search;

})();

$(function() {
  var docSearch;
  return docSearch = new Search();
});
